### ISSUE TITLE
4级标题显示有问题

### ISSUE THREAD

**Issue by chendingding1992** [dkheng/DogsChoice#3]

**Comment by dkheng** [comment]
请问您在使用中遇到什么问题，请详细描述一下

**Comment by chendingding1992** [comment]
4级标题（####） 标题显示乱码

**Comment by dkheng** [comment]
是否可以截图看一下，我无法定位您遇到什么问题

**Comment by chendingding1992** [comment]
![image](https://github.com/user-attachments/assets/d4b65b2d-4b4c-4970-b91d-276f822a6aba)

这个标题是四级标题，正常显示是5.3.1。我用了标题自动添加数字显示功能。

**Comment by dkheng** [comment]
这是自动行号和标题前装饰的冲突问题，因为”自动行号“与”H4标题前面的竖线装饰“都是使用 :before 实现的，二者存在冲突，我无法解决该问题。

**Comment by chendingding1992** [comment]
我用别的主题可以正常显示，您能告诉我怎样修改您的主题可以解决这个问题吗 谢谢

**Comment by dkheng** [comment]
主题所有源代码都在仓库里，你可以自行修改，我无法解决该问题，并不知道应该如何修改。

**Comment by chendingding1992** [comment]
![image](https://github.com/user-attachments/assets/26b483e9-aa10-4657-983e-eeb7a8d9a870)
删除红圈2行就好了

我对CSS不熟悉的，主要是c开发

**Comment by dkheng** [comment]
这样做应该是删除了四级标题前面的竖线装饰，就不会再与自动行号发生冲突。如不需要竖线装饰，自行删除即可。
